version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: demo-clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "18123:8123"  # HTTP interface
      - "19000:9000"  # Native TCP interface
    volumes:
      - ./s3.xml:/etc/clickhouse-server/config.d/s3.xml
    networks:
      - clickhouse-network
networks:
  clickhouse-network:
    driver: bridge
