input:
  generate:
    batch_size: 45
    interval: 1s
    mapping: |
      root.submarine_id = uuid_v4()
      root.timestamp = timestamp_unix()
      root.depth_feet = (10997 + (random_int(-3000, 3000) / 1000.0)) * 3.28084
      root.pressure_psi = (root.depth_feet / 3.28084) * 0.1 * 145.038
      root.coordinates = {
        "lat": 11.35 + (random_int(0, 200) / 10000.0),
        "lon": 142.19 + (random_int(0, 200) / 10000.0)
      }
      root.temp_fahrenheit = (1 + (random_int(0, 300) / 100.0)) * 9 / 5 + 32
      root.signal_db = -100 + (random_int(0, 500) / 10.0)
pipeline:
  processors:
    - bloblang: |
        root = {
            "submarine_id": this.submarine_id,
            "timestamp": this.timestamp,
            "coordinates": this.coordinates,
            "depth_feet": this.depth_feet,
            "pressure_psi": this.pressure_psi,
            "temperature_fahrenheit": this.temp_fahrenheit,
            "signal_strength_db": this.signal_db
        }
    - archive:
        format: lines
output:
  label: ""
  sftp:
    address: {YOUR_SFTP_SERVER}
    path: "upload/${! timestamp_unix() }.txt" # No default (required)
    codec: all-bytes
    credentials:
      username: {YOUR_SFTP_USERNAME}
      password: {YOUR_SFTP_PASSWORD}
    max_in_flight: 64
