input:
  sftp:
    address: {SFTP_SERVER}
    credentials:
      username: {SFTP_USERNAME}
      password: {SFTP_PASSWORD}
    paths: ["upload/*.txt"]
    codec: lines
pipeline:
  processors:
    - bloblang: |
        root.submarine_id = this.submarine_id
        root.timestamp = this.timestamp.or(this.time)
        root.latitude = this.coordinates.lat
        root.longitude = this.coordinates.lon
        root.depth = this.depth_feet / 3.28084
        root.pressure_mpa = this.pressure_psi / 145.038
        root.temperature = (this.temperature_fahrenheit - 32) * 5 / 9
        root.signal_strength_db = this.signal_strength_db
output:
  kafka_franz:
    seed_brokers:
      - localhost:19092
    topic: mariana_trench
    compression: none
