input:
  aws_sqs:
    url: "https://{YOUR_SQS_URL}/aws-sqs" # No default (required)
    region: "us-east-1"
    credentials:
      id: {YOUR_AWS_ID}
      secret: {YOUR_AWS_SECRET}
pipeline:
  processors:
    - bloblang: |
        root.submarine_id = this.sub_id
        root.timestamp = this.time
        root.latitude = this.location.latitude
        root.longitude = this.location.longitude
        root.depth = this.location.depth_meters
        root.pressure_mpa = this.pressure_mpa
        root.temperature = this.temp_celsius
        root.signal_strength_db = this.signal_db
output:
  kafka_franz:
    seed_brokers:
      - localhost:19092
    topic: mariana_trench
    compression: none
