input:
  generate:
    batch_size: 2
    interval: 3s
    mapping: |
      root.submarine_id = uuid_v4()
      root.timestamp = timestamp_unix()
      root.location.depth_meters = 10997 + (random_int(-3000, 3000) / 1000.0)
      root.pressure_mpa = root.location.depth_meters * 0.1
      # Set other location details and telemetry data
      root.location.latitude = 11.35 + (random_int(0, 200) / 10000.0)
      root.location.longitude = 142.19 + (random_int(0, 200) / 10000.0)
      root.temperature_c = 1 + (random_int(0, 300) / 100.0)  # 1 to 4 degrees Celsius
      root.signal_strength_db = -100 + (random_int(0, 500) / 10.0)  # -100 to -50 dB
pipeline:
  processors:
    - bloblang: |
        root = {
          "sub_id": this.submarine_id,
          "time": this.timestamp,
          "location": this.location,
          "temp_celsius": this.temperature_c,
          "pressure_mpa": this.pressure_mpa,
          "signal_db": this.signal_strength_db
        }
output:
  label: ""
  aws_sqs:
    url: ${SQS_URL} # No default (required)
    max_in_flight: 64
    region: ${AWS_REGION}
    credentials:
      id: ${AWS_ID}
      secret: ${AWS_SECRET}